name: Dev - Build and Deploy on main

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash


jobs:
  build:
    runs-on: mdb-dev
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
          ssh-key: ${{ secrets.GH_ACTIONS_PULL_SSH }}
      - uses: ./github-actions/setup-env
      - uses: ./github-actions/build-push-ecr
        with:
          module-name: ${{ env.CI_REPOSITORY_SLUG }}
          build-for-environment: development

  deploy:
    runs-on: mdb-dev
    needs: build
    environment:
      name: dev
      url: https://hashnode.dev.mindsdb.com/blog
    steps:
      - uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
          ssh-key: ${{ secrets.GH_ACTIONS_PULL_SSH }}
      - uses: ./github-actions/setup-env
      - uses: DevOps-Nirvana/aws-helm-multi-deploy-nodocker@v2
        with:
          environment-slug: dev
          k8s-namespace: dev
          image-tag: development-${{ env.SLUG }}
          timeout: 600s
