name: Prod - Build and Deploy on release

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash


jobs:
  build:
    runs-on: mdb-dev
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
          ssh-key: ${{ secrets.GH_ACTIONS_PULL_SSH }}
      - uses: ./github-actions/setup-env
      - uses: ./github-actions/build-push-ecr
        with:
          module-name: ${{ env.CI_REPOSITORY_SLUG }}
          build-for-environment: production
          image-ref: ${{ env.CI_REF_SLUG }}

  deploy-prod:
    runs-on: mdb-prod
    needs: [build]
    environment:
      name: prod
      url: https://mindsdb.com/blog
    steps:
      - uses: actions/checkout@v4
      - name: Pull MindsDB Github Actions
        uses: actions/checkout@v4
        with:
          repository: mindsdb/github-actions
          path: github-actions
          ssh-key: ${{ secrets.GH_ACTIONS_PULL_SSH }}
      - uses: ./github-actions/setup-env
      - uses: DevOps-Nirvana/aws-helm-multi-deploy-nodocker@v2
        with:
          environment-slug: prod
          k8s-namespace: prod
          image-tag: production-${{ env.CI_REF_SLUG }}
          timeout: 600s
